/**
 * The city's voice. Replace generic UI words with system-language.
 * Import and use in client components.
 */
export const SYSTEM = {
  // Status / lifecycle
  SCANNING: "SCANNING SIGNAL",
  SCAN_WALLET: "SCANNING WALLET",
  SCAN_CIV: "CHECKING CIV ALIGNMENT",
  SCAN_STRENGTH: "READING SIGNAL STRENGTH",
  SCAN_PRESSURE: "CALCULATING HEX PRESSURE",
  SIGNAL_FOUND: "SIGNAL FOUND",
  NO_SIGNAL: "NO SIGNAL DETECTED",
  CARRIER_DETECTED: "CARRIER DETECTED",
  NO_CARRIER: "NO CARRIER DETECTED",
  CITY_UPDATED: "CITY STATUS UPDATED",
  POSITION_RECALC: "POSITION RECALCULATED",
  EXPORT_READY: "EXPORT READY",
  PASSPORT_READY: "PASSPORT READY",
  PASSPORT_UNISSUED: "PASSPORT UNISSUED",
  BRACKET_OPEN: "BRACKET OPEN",
  BRACKET_CLOSED: "BRACKET CLOSED",
  DOCTRINE_UNSEALED: "DOCTRINE UNSEALED",
  // Actions
  ENTER_CITY: "ENTER CITY",
  SCAN_WALLET_CTA: "SCAN WALLET",
  CLAIM_SIGNAL: "CLAIM SIGNAL",
  GENERATE_CARD: "GENERATE CARD",
  OPEN_REGISTRY: "OPEN REGISTRY",
  VIEW_LEDGER: "VIEW LEDGER",
  BACK_CIV: "BACK YOUR CIV",
  UNSEAL_DOCTRINE: "UNSEAL DOCTRINE",
  // Mutations
  ARTIFACT_BURNED: "ARTIFACT BURNED",
  CIV_LOCKED: "CIV ALIGNMENT LOCKED",
  HEX_RISING: "HEX PRESSURE RISING",
  HEX_FALLING: "HEX PRESSURE FALLING",
  CITY_NOTICED: "THE CITY NOTICED",
} as const;
