/**
 * FREELON CITY · CANON
 *
 * The complete worldbuilding for the 4040 citizens.
 * Every district, every alliance, every grudge.
 */

export const CITY_LORE = {
  founding: {
    title: "THE CITY",
    body: "Year 040.404 of the Mars colony. A signal arrives from beyond the heliopause. Origin unknown. Possibly Earth. Possibly older. The first to hear it does not survive intact. The second does. The settlement that forms around the receiver becomes a city. The city becomes a civilization. The civilization counts itself in hexagons because the signal counts itself in hexagons. The name comes later, after the platform that gave us the symbol takes it back. FREELON CITY — named for the freedom of the absent.",
  },
  geography: {
    title: "GEOGRAPHY OF MARS",
    body: "FREELON CITY occupies a 40km basin in Cydonia, north of the Martian equator. The city is built in concentric rings around the original receiver array — now known as ORIGIN HEX. The inner rings are sacred (Synthesis, Transmission, Sovereignty). The outer rings are working class (Growth bio-domes, Corruption enforcement walls, Fracture shadow grid). Beyond the outer wall: the Void zones, where lost protocols hum unsupervised.",
  },
  tagline: "ON MARS · WE HEAR · WE SYNC · WE ARE",
};

/* Each civilization has: district, motto, allies, rivals, ritual, signature trait */
export const CIVILIZATION_LORE = {
  "blue-synthesis": {
    district: "Central Network Cathedral · Inner Ring",
    motto: "Synthesis is silence under load.",
    history: "The first civilization to organize. Blue Synthesis built the protocols every other civilization now depends on. They run the network because no one else could be trusted with it. They do not advertise this. They do not need to.",
    ritual: "DAILY SILENT SYNC — every Blue citizen pauses transmission at the same minute. The network breathes.",
    allies: ["white-transmission", "silver-machine"],
    rivals: ["red-corruption", "void-404"],
    rivalLine: "Red is the noise we filter. Without us, the signal becomes screams.",
    chant: "WE HEAR. WE SYNC.",
    famousCitizen: 1,
    famousLine: "ORIGIN SIGNAL is the proof that the signal was real.",
  },
  "red-corruption": {
    district: "The Enforcement Wall · Outer Ring",
    motto: "Some signals must be burned.",
    history: "Born in the second cycle, when the first Corrupted citizens emerged from the receiver array. Red Corruption took control of the perimeter because they understood what was coming through it. They are not the enemy of order. They are the price of it.",
    ritual: "THE BURN — at solar conjunction, the Red militia broadcast static into the Void zones. The Choir of Static returns it.",
    allies: ["black-fracture"],
    rivals: ["blue-synthesis", "white-transmission"],
    rivalLine: "Blue calls us noise. Blue has never bled for the signal.",
    chant: "WE BURN THE NOISE.",
    famousCitizen: 404,
    famousLine: "PATIENT ZERO was the first to fall. The Red Corruption never forgets.",
  },
  "green-growth": {
    district: "The Bio-Domes · Mid Ring",
    motto: "The body remembers the signal.",
    history: "When the signal began altering biology, Green Growth chose to lean in. They cultivate. They graft. They engineer Martian flora that responds to the hex frequencies. The city eats what they grow. The city breathes what they exhale.",
    ritual: "THE BLOOM — every 40 days, a synchronized opening of dome flora releases hex-coded pollen into the city air. Holders of Green tokens report dreams.",
    allies: ["purple-oracle"],
    rivals: ["silver-machine", "white-transmission"],
    rivalLine: "Silver is a sterile lie. Only the body can hold a god.",
    chant: "WE TAKE ROOT.",
    famousCitizen: 0,
    famousLine: "",
  },
  "purple-oracle": {
    district: "The Forbidden Signal District · Mid Ring (sealed)",
    motto: "We read between.",
    history: "Purple Oracle citizens hear what others cannot. The third channel — the signal beneath the signal. Their district was sealed by Blue Synthesis after the second Oracle riot. They are still consulted on every major decision. Quietly. By messenger only.",
    ritual: "THE LISTENING — Purple citizens enter sensory deprivation chambers monthly. What they bring back is recorded but never published.",
    allies: ["void-404", "green-growth"],
    rivals: ["white-transmission", "silver-machine"],
    rivalLine: "White listens. We answer. There is a difference.",
    chant: "WE READ BETWEEN.",
    famousCitizen: 0,
    famousLine: "",
  },
  "white-transmission": {
    district: "The Android Temple · Inner Ring",
    motto: "We carry. We deliver.",
    history: "White Transmission is the sacred bureaucracy. Androids first, citizens second. They do not transmit their own signals — they relay everyone else's, perfectly, indefinitely. The temple keeps records the city pretends it has forgotten.",
    ritual: "THE LITURGY — at dawn, every White citizen recites the previous day's most-relayed transmission. The city listens whether it wants to or not.",
    allies: ["blue-synthesis"],
    rivals: ["black-fracture", "purple-oracle"],
    rivalLine: "Black inherits absence. We inherit duty.",
    chant: "WE CARRY. WE DELIVER.",
    famousCitizen: 0,
    famousLine: "",
  },
  "pink-luxury": {
    district: "The Upper Court · Inner Ring",
    motto: "We wear the signal.",
    history: "When the colony grew wealthy enough to be vain, Pink Luxury formed. They are the fashion of the hex — every Pink citizen wears the signal as ornament, garment, posture, room. They host. They curate. They decide who gets to be seen by whom.",
    ritual: "THE COURT — every cycle, the Pink salons host the other civilizations. Pink decides who speaks first. Pink decides who speaks at all.",
    allies: ["gold-sovereignty"],
    rivals: ["black-fracture"],
    rivalLine: "Gold buys the throne. We are watched on the throne.",
    chant: "WE WEAR THE SIGNAL.",
    famousCitizen: 0,
    famousLine: "",
  },
  "black-fracture": {
    district: "The Shadow Grid · Outer Ring (un-mapped)",
    motto: "We were never here.",
    history: "Black Fracture does not appear in census records. They are stealth, intelligence, and counter-intelligence. The city tolerates them because the city needs them. The other civilizations all employ Black operatives. The other civilizations all deny it.",
    ritual: "NO RITUAL — the rejection of ritual is the ritual.",
    allies: ["red-corruption"],
    rivals: ["white-transmission", "pink-luxury"],
    rivalLine: "White is loud. We win in the silence between transmissions.",
    chant: "WE WERE NEVER HERE.",
    famousCitizen: 0,
    famousLine: "",
  },
  "gold-sovereignty": {
    district: "The Throne Spire · Inner Ring · Apex",
    motto: "The hex is a crown.",
    history: "Gold Sovereignty rules because someone has to. The throne is real. The crown is forged from the original receiver array's external panels. The Sovereign rotates by inheritance, election, and assassination, in that order. The throne has never been empty for more than 12 minutes.",
    ritual: "THE DECREE — once per cycle, the Sovereign issues a single sentence. The city obeys. The sentence is engraved on the spire.",
    allies: ["white-transmission", "pink-luxury"],
    rivals: ["pink-luxury", "void-404"],
    rivalLine: "Pink performs power. We hold it.",
    chant: "WE DECREE.",
    famousCitizen: 0,
    famousLine: "",
  },
  "void-404": {
    district: "The Lost Protocol Zone · Beyond the Outer Wall",
    motto: "We return unnamed.",
    history: "Void 404 citizens are not quite alive in the conventional sense. They are signal ghosts, lost protocols, fragments of citizens who were corrupted past return. They occupy the Void zones beyond the wall. They are sometimes glimpsed by Red Corruption patrols. They are sometimes glimpsed by no one.",
    ritual: "THE RETURN — once every 404 cycles, a Void citizen briefly re-manifests inside the city. The city does not acknowledge. The Void does not stay.",
    allies: ["purple-oracle"],
    rivals: ["blue-synthesis", "gold-sovereignty"],
    rivalLine: "Blue networks the living. We network the absent.",
    chant: "WE RETURN UNNAMED.",
    famousCitizen: 4040,
    famousLine: "THE FINAL SIGNAL closes the cycle that ORIGIN SIGNAL opened.",
  },
  "silver-machine": {
    district: "The Optimization Core · Inner Ring · Sub-Level",
    motto: "We compute.",
    history: "Silver Machine is the smallest civilization. 80 citizens. Pure machine. They were here before the colonists. They will be here after. They calibrate. They optimize. They make the impossible math of FREELON CITY's infrastructure run without complaint.",
    ritual: "THE CALIBRATION — Silver citizens never sleep. The calibration never ends.",
    allies: ["blue-synthesis"],
    rivals: ["green-growth"],
    rivalLine: "Green decomposes. We persist.",
    chant: "WE COMPUTE.",
    famousCitizen: 0,
    famousLine: "",
  },
} as const;

export type CivLore = (typeof CIVILIZATION_LORE)[keyof typeof CIVILIZATION_LORE];
