#!/usr/bin/env node
/**
 * verify-engine.mjs — drift guard for the vendored Crypt rules engine.
 *
 * The engine under `lib/crypt-engine/` is GENERATED by crypt-game's
 * `scripts/sync-engine.mjs`. If someone hand-edits a vendored file (or a sync
 * is forgotten after an engine change), the server would run rules that no
 * longer match the source of truth. To make that impossible to ship silently,
 * this re-hashes every vendored file and compares against the committed
 * `MANIFEST.sha256`. Any mismatch / missing / extra file => non-zero exit.
 *
 * Wired into the city `package.json` as `verify:engine` AND `prebuild`, so
 * `next build` fails LOUDLY on drift.
 */

import { createHash } from "node:crypto";
import {
  existsSync,
  readFileSync,
  readdirSync,
  statSync,
} from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const VENDOR = resolve(__dirname, "..", "lib", "crypt-engine");
const MANIFEST = join(VENDOR, "MANIFEST.sha256");

function fail(msg) {
  console.error(`verify:engine FAILED — ${msg}`);
  console.error(
    "  The vendored engine is out of sync with crypt-game/src.\n" +
      "  Run `npm run sync:engine` in the crypt-game repo and commit the result.",
  );
  process.exit(1);
}

if (!existsSync(MANIFEST)) {
  fail(`missing manifest: ${relative(process.cwd(), MANIFEST)}`);
}

/** Parse "  <sha>  <relpath>" lines into a map. */
const manifest = new Map();
for (const line of readFileSync(MANIFEST, "utf8").split("\n")) {
  const trimmed = line.trim();
  if (!trimmed) continue;
  const sep = trimmed.indexOf("  ");
  if (sep < 0) fail(`malformed manifest line: ${trimmed}`);
  const sha = trimmed.slice(0, sep);
  const rel = trimmed.slice(sep + 2).trim();
  manifest.set(rel, sha);
}

/** Walk the vendored tree, hashing each file (excluding the manifest itself). */
function walk(absDir, out) {
  for (const entry of readdirSync(absDir)) {
    const abs = join(absDir, entry);
    const st = statSync(abs);
    if (st.isDirectory()) walk(abs, out);
    else if (st.isFile()) out.push(abs);
  }
}

const onDisk = [];
walk(VENDOR, onDisk);

const seen = new Set();
let mismatches = 0;

for (const abs of onDisk) {
  const rel = relative(VENDOR, abs).split("\\").join("/");
  if (rel === "MANIFEST.sha256") continue;
  seen.add(rel);
  const expected = manifest.get(rel);
  if (!expected) {
    console.error(`  EXTRA (not in manifest): ${rel}`);
    mismatches++;
    continue;
  }
  const actual = createHash("sha256").update(readFileSync(abs)).digest("hex");
  if (actual !== expected) {
    console.error(`  MODIFIED: ${rel}`);
    mismatches++;
  }
}

for (const rel of manifest.keys()) {
  if (!seen.has(rel)) {
    console.error(`  MISSING (in manifest, not on disk): ${rel}`);
    mismatches++;
  }
}

if (mismatches > 0) {
  fail(`${mismatches} file(s) drifted`);
}

console.log(`verify:engine OK — ${manifest.size} vendored files match.`);
